Use Node object everywhere
jelmerveen/molgenis-py-bbmri-eric pull request #3
Opened 2021-06-17 15:35 UTC by tommydeboer

2021-06-18 07:59 UTC, jelmerveen requested changes

2021-06-18 07:59 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +def _filter_national_node_data(data: list[dict], node: Node) -> list[dict]:
list to List?

2021-06-18 07:59 UTC, jelmerveen commented on src/molgenis/bbmri_eric/nodes.py
>  def get_all_nodes() -> List[Node]:
should include the external here

2021-06-21 07:53 UTC, tommydeboer commented on src/molgenis/bbmri_eric/nodes.py
>  def get_all_nodes() -> List[Node]:
the dicts are already being combined at the module scope

2021-06-21 08:53 UTC, merged